name: NetworkSampleApp

settings: 
  MARKETING_VERSION: "1.0"
  SWIFT_VERSION: 5.7
  VERSIONING_SYSTEM: "apple-generic"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ARCHS: $(ARCHS_STANDARD)
  CODE_SIGN_IDENTITY: ""
  
options:
  xcodeVersion: "14.2"
  createIntermediateGroups: true
  developmentLanguage: "pt-BR"
  bundleIdPrefix: br.com.comitando
  deploymentTarget:
    iOS: 14.0
    macOS: 12.0

configs:
  Debug: debug
  Release: release

packages:
  LHNetworkClient:
    url: https://github.com/luizhammeli/LHNetworkClient.git
    branch: main

targets:
  NetworkSampleApp:
    templates:
      - iOSApp
    dependencies:
      - package: LHNetworkClient
    properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
  NetworkSampleAppTests:
    templates:
      - iOSAppTests
    dependencies:
      - target: NetworkSampleApp
      - package: LHNetworkClient
  NetworkSampleAppUITests:
    templates:
      - iOSAppUITests
    dependencies:
      - target: NetworkSampleApp
      - package: LHNetworkClient

schemes:
  NetworkSampleApp:
    build:
      targets:
        NetworkSampleApp: [run, test, archive]
    archive:
      config: Release
    run:
      config: Debug
    test: 
      config: Debug
      gatherCoverageData: true
      coverageTargets: 
        - NetworkSampleApp
      targets:
        - name: NetworkSampleAppTests
          randomExecutionOrder: true
        - name: NetworkSampleAppUITests
          randomExecutionOrder: true

targetTemplates:
  iOSApp:
    platform: iOS
    type: application
    sources: 
      - path: ${target_name}
    settings:
      base:
        INFOPLIST_FILE: ${target_name}/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: LuizHammerli.NetworkSampleApp
      configs:
        Release:
          CODE_SIGN_IDENTITY: ""
          PROVISIONING_PROFILE_SPECIFIER: ""
        Debug:
          CODE_SIGN_IDENTITY: ""
          PROVISIONING_PROFILE_SPECIFIER: ""

  iOSAppTests:
    platform: iOS
    type: bundle.unit-test
    sources: 
      - path: ${target_name}
    info:
      path: ${target_name}/Info.plist
  
  iOSAppUITests: 
    platform: iOS
    type: bundle.ui-testing
    sources: 
      - path: ${target_name}
    info:
      path: ${target_name}/Info.plist
